on:
  push:
    branches:
      - "main"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # check out files
      - uses: actions/setup-node@v4 # set up node
        with:
          node-version: 20 # not latest but safer for Angular
      - run: npm ci # dependencies
      - run: rm -rf dist # cleanup
      - run: npm run build -- --base-href=/db/ # force static build
      - run: cp dist/app/browser/index.html dist/app/browser/404.html # fallback 404
      - uses: actions/upload-pages-artifact@v3 # upload artifact to pages
        with:
          path: dist/app/browser
      - uses: actions/deploy-pages@v4 # deploy
