on:
  push:
    branches:
      - "main"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # check out files
      - uses: actions/setup-node@v4 # set up node
        with:
          node-version: 20 # not latest but safer for Angular
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci # dependencies
      - run: rm -rf dist # cleanup
      - run: npx ng build --configuration=production --base-href=/ # attempting SPA build
      - run: cp dist/app/index.html dist/app/404.html # fallback 404, index
      - uses: actions/upload-pages-artifact@v3 #upload artifact to pages
        with:
          path: dist/app
      - uses: actions/deploy-pages@v4 # deploy to pages
